# Generated by Django 5.0.1 on 2024-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_customerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
